# language: go
language: node_js

before_install:

  # Install Pulumi
  - curl -fsSL https://get.pulumi.com | sh
  - export PATH="/home/travis/.pulumi/bin:$PATH"
  - pulumi version
  - pulumi login

  # Install and start travisqueue
  # - go get github.com/pulumi/travisqueue
  # - travisqueue start

script:
  - ./scripts/travis_${TRAVIS_EVENT_TYPE}.sh

# after_script:
#   - travisqueue finish
